import type { Metadata } from "next";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { Footer } from "@/components/Layout/Footer";
import { AnalyticsWrapper } from "@/components/Analytics/Analytics";
import { StagewiseToolbar } from '@stagewise/toolbar-next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const stagewiseConfig = {
    plugins: []
  };

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* 只添加跳过导航链接，不修改main标签结构 */}
        <a 
          href="#content-start" 
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 z-50 bg-purple-600 text-white px-4 py-2 rounded-md focus:outline-none"
        >
          Skip to content
        </a>
        
        {/* 保持原始结构不变，只在children前添加锚点 */}
        <main className="flex-grow">
          <div id="content-start" className="outline-none" tabIndex={-1} aria-hidden="true"></div>
          {children}
        </main>
        <Footer />
        <AnalyticsWrapper />
        {process.env.NODE_ENV === 'development' && (
          <StagewiseToolbar config={stagewiseConfig} />
        )}
      </body>
    </html>
  );
}